Nsm\Bundle\AppBundle\Entity\SubTask:
    type: entity
    repositoryClass: Nsm\Bundle\AppBundle\Entity\SubTaskRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        tags:
            type: string
            length: 255
            nullable: true
        activityDurationSum:
            type: decimal
            scale: 2
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        task:
             targetEntity: Task
             inversedBy: subTasks

    oneToMany:
        activities:
            targetEntity: Activity
            mappedBy: task
            cascade:
                - remove
