NsmUserBundle:
    resource: "@NsmUserBundle/Resources/config/routing.yml"

NsmApiBundle:
    resource: "@NsmApiBundle/Resources/config/routing.yml"

NsmHelpBundle:
    resource: "@NsmHelpBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


