Nsm\Bundle\ContactCardBundle\Entity\Url:
    type: entity
    table: url
    indexes:
        fk_url_contact_card1_idx:
            columns:
                - contact_card_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            length: 45
            fixed: false
            comment: ''
        typeCustom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        value:
            type: string
            length: 45
            fixed: false
            comment: ''
        preferred:
            type: boolean
            nullable: true
            comment: ''
    manyToOne:
        contactCard:
            targetEntity: ContactCard
            cascade: {  }
            mappedBy: null
            inversedBy: urls
            joinColumns:
                contact_card_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
