parameters:

    nsm_app.entity.task.class: Nsm\Bundle\AppBundle\Entity\Task
    nsm_app.entity.task_manager.class: Nsm\Bundle\AppBundle\Entity\TaskManager
    nsm_app.entity.task_repository.class: Nsm\Bundle\AppBundle\Entity\TaskRepository
    nsm_app.event_subscriber.task_subscriber.class: Nsm\Bundle\AppBundle\EventSubscriber\TaskSubscriber

services:

    nsm_app.entity.task_repository:
        class: %nsm_app.entity.task_repository.class%
        factory_service: "doctrine.orm.entity_manager"
        factory_method: "getRepository"
        arguments:
            - %nsm_app.entity.task.class%

    nsm_app.entity.task_manager:
        class: %nsm_app.entity.task_manager.class%
        arguments:
            - %nsm_app.entity.task.class%
            - @doctrine.orm.entity_manager

    nsm_app.event_subscriber.task_subscriber:
        class: %nsm_app.event_subscriber.task_subscriber.class%
        arguments:
            - @service_container
        tags:
            - {name: "doctrine.event_subscriber", connection: "default"}

    nsm_app.form.type.task:
        class:  Nsm\Bundle\AppBundle\Form\Type\TaskType
        tags:
            - {name: form.type, alias: task}
