Nsm\Bundle\HelpBundle\Entity\Tip:
    type: entity
    repositoryClass: Nsm\Bundle\HelpBundle\Entity\TipRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
            nullable: true
        route:
            type: string
            length: 255
