tip_browse:
    pattern: '/tips.{_format}'
    defaults: { _controller: 'NsmHelpBundle:Tips:browse', _format: ~ }
    requirements: { _method: 'GET' }

tip_read:
    pattern: '/tips/{id}'
    defaults: { _controller: 'NsmHelpBundle:Tips:read' }
    requirements: { _method: 'GET', id: '\d+'}

tip_add:
    pattern: '/tips/new'
    defaults: { _controller: 'NsmHelpBundle:Tips:add' }
    requirements: { _method: 'GET' }

tip_post:
    pattern: '/tips'
    defaults: { _controller: 'NsmHelpBundle:Tips:add' }
    requirements: { _method: 'POST' }

tip_edit:
    pattern: '/tips/{id}/edit'
    defaults: { _controller: 'NsmHelpBundle:Tips:edit' }
    requirements: { _method: 'GET' }

tip_patch:
    pattern: '/tips'
    defaults: { _controller: 'NsmHelpBundle:Tips:edit' }
    requirements: { _method: 'PATCH' }

tip_destroy:
    pattern: '/tips/{id}/remove'
    defaults: { _controller: 'NsmHelpBundle:Tips:destroy' }
    requirements: { _method: 'GET' }

tip_delete:
    pattern: '/tips'
    defaults: { _controller: 'NsmHelpBundle:Tips:destroy' }
    requirements: { _method: 'DELETE' }
