services:
    nsm_contact_card.entity.contact_card_manager:
        class: Nsm\Bundle\ContactCardBundle\Entity\ContactCardManager
        arguments:
            - Nsm\Bundle\ContactCardBundle\Entity\ContactCard
            - @doctrine.orm.entity_manager

    nsm_contact_card.entity.contact_card_repository:
        class: Nsm\Bundle\ContactCardBundle\Entity\ContactCardRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: "getRepository"
        arguments: [ Nsm\Bundle\ContactCardBundle\Entity\ContactCard ]

    nsm_contact_card.form.data_transformer.contact_card_to_preferred_values_transformer:
        class: Nsm\Bundle\ContactCardBundle\Form\DataTransformer\ContactCardToPreferredValuesTransformer
        arguments:
            - @nsm_contact_card.entity.contact_card_manager

    nsm_contact_card.form.type.contract_create_contact_card_type:
        class: Nsm\Bundle\ContactCardBundle\Form\Type\ContactCardSimpleType
        arguments:
            - @nsm_contact_card.form.data_transformer.contact_card_to_preferred_values_transformer
        tags:
            - {name: "form.type", alias: "contact_card_simple"}
